//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fgModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_models_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_models_t()
        {
            this.siixsem_sidesModel_td = new HashSet<siixsem_sidesModel_td>();
        }
    
        public int se_id_model { get; set; }
        public string se_description { get; set; }
        public int se_id_family { get; set; }
        public int se_is_special { get; set; }
        public int se_valid { get; set; }
        public int se_serial_continuos { get; set; }
        public int se_two_led { get; set; }
        public int se_dfc_ifc { get; set; }
        public int se_four_sides { get; set; }
        public int se_cover_frame { get; set; }
        public float se_num_pcb { get; set; }
        public int se_laser_mark { get; set; }
        public int se_has_panelLbl { get; set; }
        public int se_is_ldm { get; set; }
        public int se_one_step { get; set; }
        public int se_two_step { get; set; }
        public int se_three_step { get; set; }
        public int se_xml { get; set; }
        public int se_is_pallet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_sidesModel_td> siixsem_sidesModel_td { get; set; }
    }
}
